/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.huya.search.rpc;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RpcResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6706286157701453374L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RpcResult\",\"namespace\":\"com.huya.search.rpc\",\"fields\":[{\"name\":\"result\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"RpcResultRow\",\"fields\":[{\"name\":\"resultRow\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RpcResult> ENCODER =
      new BinaryMessageEncoder<RpcResult>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RpcResult> DECODER =
      new BinaryMessageDecoder<RpcResult>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RpcResult> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RpcResult> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RpcResult>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RpcResult to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RpcResult from a ByteBuffer. */
  public static RpcResult fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<com.huya.search.rpc.RpcResultRow> result;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RpcResult() {}

  /**
   * All-args constructor.
   * @param result The new value for result
   */
  public RpcResult(java.util.List<com.huya.search.rpc.RpcResultRow> result) {
    this.result = result;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return result;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: result = (java.util.List<com.huya.search.rpc.RpcResultRow>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'result' field.
   * @return The value of the 'result' field.
   */
  public java.util.List<com.huya.search.rpc.RpcResultRow> getResult() {
    return result;
  }

  /**
   * Sets the value of the 'result' field.
   * @param value the value to set.
   */
  public void setResult(java.util.List<com.huya.search.rpc.RpcResultRow> value) {
    this.result = value;
  }

  /**
   * Creates a new RpcResult RecordBuilder.
   * @return A new RpcResult RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new RpcResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RpcResult RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new RpcResult RecordBuilder by copying an existing RpcResult instance.
   * @param other The existing instance to copy.
   * @return A new RpcResult RecordBuilder
   */
  public static Builder newBuilder(RpcResult other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for RpcResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RpcResult>
    implements org.apache.avro.data.RecordBuilder<RpcResult> {

    private java.util.List<com.huya.search.rpc.RpcResultRow> result;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.result)) {
        this.result = data().deepCopy(fields()[0].schema(), other.result);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RpcResult instance
     * @param other The existing instance to copy.
     */
    private Builder(RpcResult other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.result)) {
        this.result = data().deepCopy(fields()[0].schema(), other.result);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'result' field.
      * @return The value.
      */
    public java.util.List<com.huya.search.rpc.RpcResultRow> getResult() {
      return result;
    }

    /**
      * Sets the value of the 'result' field.
      * @param value The value of 'result'.
      * @return This builder.
      */
    public Builder setResult(java.util.List<com.huya.search.rpc.RpcResultRow> value) {
      validate(fields()[0], value);
      this.result = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'result' field has been set.
      * @return True if the 'result' field has been set, false otherwise.
      */
    public boolean hasResult() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'result' field.
      * @return This builder.
      */
    public Builder clearResult() {
      result = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RpcResult build() {
      try {
        RpcResult record = new RpcResult();
        record.result = fieldSetFlags()[0] ? this.result : (java.util.List<com.huya.search.rpc.RpcResultRow>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RpcResult>
    WRITER$ = (org.apache.avro.io.DatumWriter<RpcResult>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RpcResult>
    READER$ = (org.apache.avro.io.DatumReader<RpcResult>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
