/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.huya.search.rpc;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SalverRpcProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SalverRpcProtocol\",\"namespace\":\"com.huya.search.rpc\",\"types\":[{\"type\":\"record\",\"name\":\"RpcResultRow\",\"fields\":[{\"name\":\"resultRow\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]},{\"type\":\"record\",\"name\":\"RpcResult\",\"fields\":[{\"name\":\"result\",\"type\":{\"type\":\"array\",\"items\":\"RpcResultRow\"}}]},{\"type\":\"record\",\"name\":\"RpcRefreshContext\",\"fields\":[{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"unixTime\",\"type\":\"long\"}]}],\"messages\":{\"refresh\":{\"request\":[{\"name\":\"refreshContext\",\"type\":\"RpcRefreshContext\"}],\"response\":\"null\"},\"sql\":{\"request\":[{\"name\":\"queryBytes\",\"type\":\"bytes\"},{\"name\":\"shardArray\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"shardNum\",\"type\":\"int\"}],\"response\":\"RpcResult\"},\"syncPullTask\":{\"request\":[],\"response\":\"string\"},\"openPullTask\":{\"request\":[{\"name\":\"serviceUrl\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"shardId\",\"type\":\"int\"},{\"name\":\"method\",\"type\":\"string\"}],\"response\":\"null\"},\"closePullTask\":{\"request\":[{\"name\":\"serviceUrl\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"shardId\",\"type\":\"int\"}],\"response\":\"null\"},\"closePullTaskList\":{\"request\":[{\"name\":\"serviceUrl\",\"type\":\"string\"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"shardIds\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}],\"response\":\"null\"},\"insertStat\":{\"request\":[],\"response\":\"string\"},\"shutdown\":{\"request\":[],\"response\":\"null\"}}}");
  /**
   */
  Void refresh(RpcRefreshContext refreshContext) throws org.apache.avro.AvroRemoteException;
  /**
   */
  RpcResult sql(java.nio.ByteBuffer queryBytes, java.util.List<Integer> shardArray, int shardNum) throws org.apache.avro.AvroRemoteException;
  /**
   */
  CharSequence syncPullTask() throws org.apache.avro.AvroRemoteException;
  /**
   */
  Void openPullTask(CharSequence serviceUrl, CharSequence table, int shardId, CharSequence method) throws org.apache.avro.AvroRemoteException;
  /**
   */
  Void closePullTask(CharSequence serviceUrl, CharSequence table, int shardId) throws org.apache.avro.AvroRemoteException;
  /**
   */
  Void closePullTaskList(CharSequence serviceUrl, CharSequence table, java.util.List<Integer> shardIds) throws org.apache.avro.AvroRemoteException;
  /**
   */
  CharSequence insertStat() throws org.apache.avro.AvroRemoteException;
  /**
   */
  Void shutdown() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SalverRpcProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = SalverRpcProtocol.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void refresh(RpcRefreshContext refreshContext, org.apache.avro.ipc.Callback<Void> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void sql(java.nio.ByteBuffer queryBytes, java.util.List<Integer> shardArray, int shardNum, org.apache.avro.ipc.Callback<RpcResult> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void syncPullTask(org.apache.avro.ipc.Callback<CharSequence> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void openPullTask(CharSequence serviceUrl, CharSequence table, int shardId, CharSequence method, org.apache.avro.ipc.Callback<Void> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void closePullTask(CharSequence serviceUrl, CharSequence table, int shardId, org.apache.avro.ipc.Callback<Void> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void closePullTaskList(CharSequence serviceUrl, CharSequence table, java.util.List<Integer> shardIds, org.apache.avro.ipc.Callback<Void> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void insertStat(org.apache.avro.ipc.Callback<CharSequence> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void shutdown(org.apache.avro.ipc.Callback<Void> callback) throws java.io.IOException;
  }
}